apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-core2
spec:
  selector:
    matchLabels:
      app: myapp-core2
  template:
    metadata:
      labels:
        app: myapp-core2
    spec:
      imagePullSecret:
        - name: regcred
      containers:
        - name: myapp-core2
          image: rudicatsmile2/simple-webapp:1
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
