apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: core
resources:
  - namespace.yaml
  - deployment.yaml
  - payment-service
  - ../../modules/dockersecret.yaml
  - ../../modules/dockersecretapp.yaml
