apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:kYbsuW1zUHz6NguqXxg0O8DQaybLfkIrgtD2vk3yatdnpzuKyZTZCUeQT+r+iO6+uwDZev43Op8b+KmpZ6Wq4/GiR9fFNuhsNCsvT0WIYPvtEvCSQfEa1XPxY4lQ0LECLFgYgV/+/V3X5UXW31g7Or84OrM+uEdAgE9IO9DpLa7PMtJ05LxXTz2S4Ho4nPcPAK9PQCfAhUMDJ7vQ3eVDDrCAO87Wf2N6WzFp0S8KjDs0WsbekN15FDaQwuDg4faHLvIWsSEAGW8JCJprikKjZtphEnxdc5/Yr9JQct2wJQDU6umgHPz8x4inROggG/0YiLvNyCyPHeZZXJ4l51LYVECN8FrF3udJ,iv:AGQhLk1bq3eaoSqd70wprNOHXTE+NnAQy1WH97gnCWQ=,tag:DGw4L5144ojuzb6TUQu90A==,type:str]
kind: Secret
metadata:
  # creationTimestamp: null
  name: regcredapp
type: kubernetes.io/dockerconfigjson
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1w90ws7aq28ltpwjpz7acl8semvlcd0ch4e5l40fpwuqfsy26rewqzcftlc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOVRiOVVUVTdYd2NOMDRG
        YzUwOHpDMFdVRUNnNVZSQ29LVlNJL0ZuNzFZCjRGYmNTcUIxUmlXTkw4dk5ldW1R
        ZzBtR3ZocStEdW1zcEJEYlk5Z0pxREkKLS0tIFJDRHNrdnN2UlRaMjZpOHA4d3RG
        ZkNYV0JtL0pocmQ1UjNrbHFDNnB2dHcKU+C5udyvFOTegbmh96yJqk/JrjOZLsEZ
        g6+iyDudKvou9N8q0Bz0lA2XHCF+QcGyFsQKd+zK/rqXw8moXoUZ3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-08-23T06:33:06Z"
  mac: ENC[AES256_GCM,data:cr9BVDGtnS8BtaqjuWYtAw06z+buHxq4sa+248anWUrpnIXRGQOqFrRkck/3vEg6I5XqnyGk2EgE0bS4iqlbTmWebJNOyEaEUnVrnll2IsvaqHXQJRX3POTc0xYWhwbSe29VHi61tPp8hZggtz3KP3vuPS9ORDwCLleKLrbrK1I=,iv:3UI3COGWnnVoDkUAqw+lXTRyvI1U8NpvWzP67oIG9w4=,tag:A5hy2qWirY7UByWeAMTkSg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
