apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-core-simple-webapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecret:
        - name: regcred2
      containers:
        - name: myapp
          # image: nginx:alpine
          image: rudicatsmile2/simple-webapp:1

          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
