apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-simple-webapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: regcred2
      containers:
        - name: myapp
          # image: nginx:alpine
          # image: rudicatsmile2/simple-webapp:1 # {"$imagepolicy": "flux-system:simplewebapp-policy"}
          image: rudicatsmile2/simplelandingpage:1 # {"$imagepolicy": "flux-system:simplewebapp-policy"}
          resources:
            limits:
              memory: "64Mi"
              cpu: "50m"
          ports:
            - containerPort: 80
