apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: simplewebapp-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: simplewebapp #metadata-name: from image-repository.yaml
  policy:
    numerical:
      order: asc
