apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: simplewebapp
  namespace: flux-system
spec:
  secretRef:
    name: regcred2
  # image: rudicatsmile2/simple-webapp
  image: rudicatsmile2/simplelandingpage
  interval: 1m
